# Generated by Django 5.1.1 on 2025-03-05 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='uploadedFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=260)),
                ('owner', models.CharField(max_length=50)),
                ('created', models.DateTimeField(verbose_name='Date Created')),
                ('updated', models.DateTimeField(verbose_name='Last Updated')),
                ('path', models.CharField(max_length=500)),
            ],
        ),
    ]
